# Generated by Django 5.1.3 on 2025-08-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
